http_server:
  # address: "0.0.0.0:8082"
  # host: "0.0.0.0"
  port: "8082"

database:
  # host: "postgres" # используем если будем запускать приложение через docker-compose
  host: "localhost" # используем если будем запускать приложение локально
  port: "5432"
  user: "wb_user"
  name: "wb_orders"
  # password: "wb_pass"

kafka:
  # host: "wb_kafka"
  # port: "9092"
  # broker: "kafka:9092" # используем если будем запускать приложение через docker-compose
  broker: "localhost:29092" # используем если будем запускать приложение локально
  zookeeper: "wb_zookeeper:2181"
  topic: "orders"
  groupID: "my_group"